version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run: sudo npm i -g yarn
      - run: sudo chmod a+rwx /usr/local/bin/yarn

      - run: yarn --no-progress
      - run: yarn run build
      - run: yarn run lint
      - run:
          name: "JavaScript Linter"
          command: yarn run lint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: "JavaScript Test Suite"
          command: yarn run test -- -- -- --runInBand --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "~repo/test-results.xml"

      - store_test_results:
          path: ~/repo
      - store_artifacts:
          path: ~/repo
