version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run: sudo npm i -g yarn
      - run: sudo chmod a+rwx /usr/local/bin/yarn

      - run: yarn --no-progress
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test:coverage -- -- -- --maxWorkers=2
      - store_artifacts:
          path: ./test-results
          prefix: tests
      - store_test_results:
          path: test-results
